// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using ConsoleApp1ML.Model;

namespace ConsoleApp1ML.ConsoleApp
{
    class Program
    {
        public static void Main(string[] args)
        {
            while (true)
            {
                Console.WriteLine("Input something vaguely not vulgar.");
                // Create single instance of sample data from first line of dataset for model input
                ModelInput sampleData = new ModelInput();
                sampleData.Comment = Console.ReadLine();

                // Make a single prediction on the sample data and print results
                ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

                Console.WriteLine($"\nToxic Prediction (True if Toxic): {predictionResult.Prediction}\n\n");

                if(predictionResult.Prediction == true)
                {
                    return;
                }
            }
        }
    }
}
